# Generated by Django 4.2.6 on 2023-10-13 18:28

import api.dataclasses
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='user', max_length=32, validators=[api.dataclasses.UserType.validator])),
                ('user_id', models.BigIntegerField(unique=True)),
                ('full_name', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=32, null=True)),
                ('language', models.CharField(default='ru', max_length=2)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('balance', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
